### ISSUE TITLE
Rename devtest and test in the config

### ISSUE THREAD

**Issue by gregtatum** [mozilla/firefox-translations-training#1071]
```yaml
datasets:
  devtest:
    - flores_dev
    - sacrebleu_wmt19
    - sacrebleu_wmt17
  test:
    - flores_devtest
    - sacrebleu_wmt20
    - sacrebleu_wmt18
```

These terms are ambiguous and confusing. For instance flores uses them in the opposite way. We can rename them to be more precise.

```yaml
datasets:
  # Used during training.
  validation:
    - flores_dev
    - sacrebleu_wmt19
    - sacrebleu_wmt17
  # Used for the final model evaluation.
  evaluation:
    - flores_devtest
    - sacrebleu_wmt20
    - sacrebleu_wmt18
```
