### ISSUE TITLE
Extend supported language codes

### ISSUE THREAD

**Issue by gregtatum** [mozilla/firefox-translations-training#1139]
A large class of errors in the pipeline on the H1-2025 run is that of language tag matching.

Our config only supports ISO 639-1 language tags with the `src` and `trg` properties. In bash and python we can convert them to ISO 639-3. We don't support scripts such as `Latn`, `Hans`, and `Hant`. There are also language tags that are using an outdated form. In ICU there is a method to normalize naming tags, but we essentially need to do the reverse. What this turns into is a large list of scattered `if` checks for certain locales the require a different format of the language code.

There is a related issue with language tag specificity. For instance `no` is the Norwegian macro language, which `nb` and `nn` are the Bokmål and Nynorsk languages respectively. Training `no-en` is fine to have a macro language on the src side, but we'll need to pick either `nb` or `nn` for things like monocleaner. This would be easier done if we can specify that in the config.

```yaml
src:
  label: no # Used in task labels
  bcp_47: no-Latn # -Latn is optional here, as it can be deduced by likely subtags.
  bcp_47_fallbacks: ["nb", "nn"]
```

We can use the label tag to help disambiguate for CI, since BCP 47 can contain non-label friendly characters.

```yaml
src:
  label: zh_hans
  bcp_47: zh-Hans
```

Here we can use ICU to get the likely subtags as needed, to deduce the `Latn`.

We can also create a more generalized fallback for cases that don't strictly follow the standards, or have some odd historic choices. Those would be used literally when no matches were found. They should be checked as a last resort since they can lead to false positive matches.

```
src:
  label: sq
  bcp_47: sq
  strict_fallbacks: ["als_Latn", "als"]
```

Using BCP 47 will also start to unlock region-based configs, such as `es-MX` vs `es-ES` (Mexican Spanish vs Spain Spanish).
