### ISSUE TITLE
Unstable training with OpusTrainer

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#314]
It seems one of the training stages in OpusTrainer (the one that includes back-translations) reduces performance of the model. Probably it's because now we start training with the original corpus and then switch to the mixed one. Maybe it's not the best idea because the training will likely stop with early-stopping and we can't control training parameters separately for now. Related to #293 

For now we can either disable back-translations completely until proving in an experiment that they help or try changing the stages to something like a little of mixed back-translations first and then fine-tuning on the original corpus + increasing early-stopping to 30 or 40 from the default 20.

Current config:

```
datasets:
  original: <dataset0> # Original parallel corpus
  backtranslated: <dataset1> # Back-translated data

stages:
  - start
  - mid
  - end
  - finetune

 # One epoch of only original high-quality data to warm up the model
start:
  - original 1.0
  - until original 1

# Gradually add back-translations to the mix
# Back-translated corpus can vary a lot in size, so we can try using original to count epochs
mid:
  - original 0.7
  - backtranslated 0.3
  - until original 1

# Expand back-translations
end:
  - original 0.6
  - backtranslated 0.4
  - until original 1

# Fine-tuning only on original clean corpus until the early stopping
finetune:
  - original 1.0
  - until original inf
```
Graphs for en-hu:
<img width="1752" alt="Screenshot 2023-12-18 at 12 24 05 PM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/07dd6a0a-9404-4358-9bcd-7b94c5dfd71c">

**Comment by eu9ene** [comment]
I've rerun it with a simpler config with reduced back-translations but one of the teachers didn't train completely. 

```
datasets:
  original: <dataset0> # Original parallel corpus
  backtranslated: <dataset1> # Back-translated data

stages:
  - pretrain
  - finetune


pretrain:
  - original 0.7
  - backtranslated 0.3
  - until original 2

# Fine-tuning only on original clean corpus until the early stopping
finetune:
  - original 1.0
  - until original inf
```
<img width="1091" alt="Screenshot 2023-12-22 at 11 25 45 AM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/04b9ab29-1d0c-43c1-bbf3-977b47b5d14e">

The corpus with back-translations produced by the script looks normal (mono.lten.tsv 200M sentences), the sentences are parallel. 

It looks like there's a bug in mixing in OpusTrainer. I think negative slope and lack of training happens because it feeds noise to Marian. I'll try to produce a corpus with OpusTrainer for further inspection.
