### ISSUE TITLE
Override default opus-trainer config from experiment config

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#426]
We'll want to experiment more with the modifiers and training data composition. Editing code adds friction to experimentation.

The experiment config might look like:

```yaml
opus-trainer:
  teacher:
    stages:
      - pretrain
      - finetune
    pretrain:
      - original 0.6
      - backtranslated 0.4
      - until original 2
    finetune:
      - original 1.0
      - until original inf
  student:
    modifiers:
    - UpperCase: 0.07 # Apply randomly to 7% of sentences
    - TitleCase: 0.05
    - Typos: 0.05
    - Noise: 0.0005
      min_word_length: 2 # Minimum word length for each word in the noisy sentence
      max_word_length: 5 # Maximum word length for each word in the noisy sentence
      max_words: 6 # Maximum number of words in each noisy sentence
```
