### ISSUE TITLE
Crash on attempt to get datasets from Opus

### ISSUE THREAD

**Issue by XapaJIaMnu** [mozilla/firefox-translations-training#47]
Hi, I'm testing the latest version with nl-en/en-nl models and I run into several crashes like this one:

```
[Thu Jan  6 20:40:34 2022]
Job 140: Splitting monolingual trg dataset
Reason: Missing output files: /mnt/mimir0/nbogoych/data/data/en-nl/snakemake-en-nl/translated/mono_trg
Downstream jobs will be updated after completion.

Activating conda environment: /mnt/mimir0/firefox-translations-training/.snakemake/conda/316f8d637776ef821bee8959d04cdacd
InputFunctionException in line 566 of /mnt/mimir0/firefox-translations-training/Snakefile:
Error:
  AttributeError: 'NoneType' object has no attribute 'get'
Wildcards:
  dataset=opus_DGT/v2019
Traceback:
  File "/mnt/mimir0/firefox-translations-training/Snakefile", line 597, in <lambda>
```

The dataset could be any, I got the same error one with CCMatrix or ELRA. 

Ideas?

Here's my config:
```yml
$ cat configs/config.nlen.yml 
####
# Example of a production config
# Change language pair, experiment name, datasets and other settings if needed
# Training low resource languages might require more tuning of pipeline/training/configs
###


# These settings depend on execution environment
# They are set in the Makefile
root: ""
cuda: ""
deps: false
gpus: ""
numgpus: ""
workspace: ""
mariancmake: ""


experiment:
  name: snakemake-nl-en
  src: nl
  trg: en

  teacher-ensemble: 2
  # path to a pretrained backward model (optional)
  backward-model: ""

  # limits per downloaded dataset
  mono-max-sentences-src: 100000000
  mono-max-sentences-trg: 20000000
  # split corpus to parallelize translation
  split-length: 2000000
  # vocab training sample
  spm-sample-size: 10000000

  best-model: chrf

  bicleaner:
    default-threshold: 0
    dataset-thresholds:
      # 0 = skip filtering
      #opus_ParaCrawl/v8: 0


marian-args:
# these configs override pipeline/train/configs
  training-backward:
    # change based on available training data
    after: 10e
  training-teacher-all:
    # remove for low resource languages or if training without augmentation
    after: 5e
# these configs override pipeline/translate/decoder.yml
  decoding-backward:
    # 12 Gb GPU, s2s model
    mini-batch-words: 2000
    # 2080ti or newer
    precision: float16
  decoding-teacher:
    # 12 Gb GPU, ensemble of 2 teachers
    mini-batch-words: 1000
    # 2080ti or newer
    precision: float16


datasets:
  # parallel training corpus
  train:
    - opus_bible-uedin/v1
    - opus_Wikipedia/v1.0
    - opus_OpenSubtitles/v2018
    - opus_ELRC_2922/v1
    - opus_QED/v2.0a
    - opus_WikiMatrix/v1
    - opus_CCMatrix/v1
    - opus_ELRC_2923/v1
    - opus_JRC-Acquis/v3.0
    - opus_TED2013/v1.1
    - opus_EUconst/v1
    - opus_GlobalVoices/v2018q4
    - opus_ELITR-ECA/v1
    - opus_CCAligned/v1
    - opus_GNOME/v1
    - opus_wikimedia/v20210402
    - opus_ECB/v1
    - opus_ELRA-W0301/v1
    - opus_ParaCrawl/v8
    - opus_Tanzil/v1
    - opus_KDE4/v2
    - opus_EUbookshop/v2
    - opus_News-Commentary/v16
    - opus_XLEnt/v1.1
    - opus_Books/v1
    - opus_ELRC_3382/v1
    - opus_TED2020/v1
    - opus_Tatoeba/v2021-07-22
    - opus_EMEA/v3
    - opus_DGT/v2019
    - opus_Europarl/v8
    - opus_Ubuntu/v14.10
    - opus_TildeMODEL/v2018
    - opus_PHP/v1
  # datasets to merge for validation while training
  devtest:
    - custom-corpus_/mnt/elli0/nbogoych/eu-dcep.tail3k
  # datasets for evaluation
  test:
    - custom-corpus_/mnt/elli0/nbogoych/eu-dcep.tail3k
  # monolingual datasets (ex. paracrawl-mono_paracrawl8, commoncrawl_wmt16, news-crawl_news.2020)
  # to be translated by the teacher model
  mono-src:
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
  # to be translated by the backward model to augment teacher corpus with back-translations
  # leave empty to skip augmentation step (high resource languages)
  mono-trg:
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
```
