### ISSUE TITLE
Support training continuation (pretrained models) for teacher ensembles

### ISSUE THREAD

**Issue by gregtatum** [mozilla/firefox-translations-training#542]
The training_continuation.py doesn't correctly handle multiple URLs.

Steps to reproduce:

Set the config

```
experiment:
  pretrained-models:
    train-teacher:
      urls:
        - https://example.com/a
        - https://example.com/b
      mode: use
      type: default
```

Run `task preflight-check`

Open `artifacts/full-task-graph.json`.

Search for both `example.com/a` and `example.com/b` in the generated tasks. `train-teacher-XX-XX-1/2` and `train-teacher-XX-XX-2/2` both contain the same files, and the URLs aren't split between them.
